export enum CommonDiv {
  BANK = 'BANK',
  PROVIDER = 'PROVIDER',
  PROVIDER_TOPUP = 'PROVIDER_TOPUP',
  PAYMENT_METHOD = 'PAYMENT_METHOD',
  PAYMENT_METHOD_PURCHASE = 'PAYMENT_METHOD_PURCHASE',
  PAYMENT_METHOD_TOPUP = 'PAYMENT_METHOD_TOPUP',
  PAYMENT_METHOD_DISBURSEMENT = 'PAYMENT_METHOD_DISBURSEMENT',
  PAYMENT_METHOD_WITHDRAW = 'PAYMENT_METHOD_WITHDRAW',
}
