import { ApiProperty } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsNumber, IsString, ValidateIf } from 'class-validator';
import Decimal from 'decimal.js';
import { ToDecimal } from 'src/shared/decorator/decimal.decorator';

export class PakaidonkCreatePurchaseQrisRequestSystemDto {
  @IsString()
  @ApiProperty()
  pakaidonkMerchantId: string;

  @IsString()
  @ApiProperty()
  pakaidonkStoreId: string;

  @IsString()
  @ApiProperty()
  pakaidonkTerminalId: string;

  @ApiProperty({ type: String })
  @IsString()
  orderId: string; // X-EXTERNAL-ID (Header) - 	Messaging reference Unique ID generated by the merchant. Numeric String. Reference number must be unique on the same day.

  @ToDecimal()
  @Type(() => Decimal)
  @ValidateIf((o) => o.nominal !== undefined)
  @ApiProperty()
  nominal: Decimal;

  @IsString()
  @ApiProperty()
  code: string;

  @IsNumber()
  @Type(() => Number)
  @ApiProperty()
  expireSecond: number;
}
